In [1]:
import numpy as np
import pandas as pd
import math
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from sklearn import decomposition
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import ElasticNet
from matplotlib import pyplot as plt
import matplotlib.style as style

import plotly
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
plotly.plotly.sign_in('spersad', 'oNkuP1yzbpN734Ag8M9P')
import plotly.graph_objs as go

from IPython.core.display import display, HTML


In [64]:
def performPCA(X, Y, num_examples=2000, metric='euclidean'):
    from sklearn.decomposition import PCA
    model = PCA(n_components=3) # fit into 2D space
    print('Defined model')
    print('Performing PCA on data with shape {0}'.format(X.shape))        
    embeddedX = model.fit_transform(X)
    print('Variance explained by selected components')
    print(model.explained_variance_ratio_)
    # Scatter plot to visualize embedded data
    # Create a trace
    trace = go.Scatter(
        x = embeddedX[:,0],
        y = embeddedX[:,1],
        mode = 'markers',
        marker=dict(
            size='5',
            color = Y, # color points by label they belong to
            colorscale= [[0, '#dd2c4f'], [1, '#3d6fcc']],
        ),
        #text = Y#[str(x) for x in X]
    )

    data = [trace]
    
    layout = go.Layout(
        title='PCA Embedding of Clusters in 2D Space',
    )

    fig = go.Figure(data=data, layout=layout)
    iplot(fig, filename='PCA-embedding')
    
    print('Plotted data')

In [146]:

data = pd.read_csv('data_CNA.xls.txt',sep='\t')
labels= pd.read_csv('OLD_DATA/data_clinical_sample_clean.tsv',sep='\t')

data.set_index('Hugo_Symbol', inplace=True)
labels.set_index('SAMPLE_ID', inplace=True)

data.drop(['Entrez_Gene_Id'], axis=1,inplace=True)
labels.drop(['Unnamed: 0'], axis=1,inplace=True)
data = data.transpose() # Convert data to matrix, rows are tumour samples

labels = labels['ONCOTREE_CODE']
result = pd.concat([data, labels], axis=1)
result.head()

result = result[result.index.str.contains("MBC-MBCProject_43UpSwhz-Tumor-SM-DL4W8") == False]


labels=result['ONCOTREE_CODE']
result.drop('ONCOTREE_CODE', axis=1, inplace=True)

X = result.as_matrix() 
Y = labels

print(X.shape)

genes = np.array(data.columns)

(102, 23109)


In [144]:
result

DDX11L1  WASH7P  hsa-mir-1302-2  \
MBC-MBCProject_1ps2hZH8-Tumor-SM-DL4OO       -1      -1              -1   
MBC-MBCProject_1qhlIasw-Tumor-SM-AXGNH        0       0               0   
MBC-MBCProject_27uAugT4-Tumor-SM-DL45T        0       0               0   
MBC-MBCProject_3LI1TNs3-Tumor-SM-DL43B        0       0               0   
MBC-MBCProject_3MUnT7Ty-Tumor-SM-CGLLE        0       0               0   
MBC-MBCProject_3jhES9fq-Tumor-SM-AXGIU        0       0               0   
MBC-MBCProject_43UpSwhz-Tumor-SM-DL4W8        0       0               0   
MBC-MBCProject_4DIpSBFV-Tumor-SM-CGM2Q        0       0               0   
MBC-MBCProject_4MF1FlFQ-Tumor-SM-AZ5CU        0       0               0   
MBC-MBCProject_4MF1FlFQ-Tumor-SM-CGM4M        0       0               0   
MBC-MBCProject_4OIOfAt9-Tumor-SM-CGLYL        1       1               1   
MBC-MBCProject_4vC6Fgio-Tumor-SM-CGLZ8        1       1               1   
MBC-MBCProject_57iLiJIl-Tumor-SM-CGLIV       -1      -1              -1   
MBC-MBCProject_5jSPs9fl-Tumor-SM-CGL1A        0       0               0   
MBC-MBCProject_70CxiQFk-Tumor-SM-DL3TI        0       0               0   
MBC-MBCProject_74CYIyHw-Tumor-SM-DL3P4        0       0               0   
MBC-MBCProject_7JtRIPI2-Tumor-SM-CGLXC        0       0               0   
MBC-MBCProject_7JtRIPI2-Tumor-SM-CGMAW        0       0               0   
MBC-MBCProject_7OcOivcV-Tumor-SM-DL44K        0       0               0   
MBC-MBCProject_7VFnIqfw-Tumor-SM-CGL6X        0       0               0   
MBC-MBCProject_7XFmtytw-Tumor-SM-DL457        0       0               0   
MBC-MBCProject_7of5i3hp-Tumor-SM-CGMAA        0       0               0   
MBC-MBCProject_99CdCOHm-Tumor-SM-AZ5MW       -1      -1              -1   
MBC-MBCProject_9JI1fwuX-Tumor-SM-DL4TP        0       0               0   
MBC-MBCProject_AqtYu0IW-Tumor-SM-DL3YJ        0       0               0   
MBC-MBCProject_AqtYu0IW-Tumor-SM-DL4Y4        0       0               0   
MBC-MBCProject_BOHWtZT8-Tumor-SM-CGLQF        0       0               0   
MBC-MBCProject_BOHWtZT8-Tumor-SM-CGM6I        0       0               0   
MBC-MBCProject_BVHET8iq-Tumor-SM-CGLGD        0       0               0   
MBC-MBCProject_DDUmIZuW-Tumor-SM-DL3GX        0       0               0   
...                                         ...     ...             ...   
MBC-MBCProject_ePi1smiM-Tumor-SM-CGLOK        0       0               0   
MBC-MBCProject_ePi1smiM-Tumor-SM-CGME2        0       0               0   
MBC-MBCProject_ePi1smiM-Tumor-SM-CGMFX        0       0               0   
MBC-MBCProject_epUYsdCE-Tumor-SM-DL3A1        0       0               0   
MBC-MBCProject_gKsRsqTR-Tumor-SM-AZ5J5       -1      -1              -1   
MBC-MBCProject_gjhMuoha-Tumor-SM-AXGGJ        0       0               0   
MBC-MBCProject_gotjfgf0-Tumor-SM-AXGPS        0       0               0   
MBC-MBCProject_gotjfgf0-Tumor-SM-CGL7K        0       0               0   
MBC-MBCProject_j2F2sQC0-Tumor-SM-DL3CJ        0       0               0   
MBC-MBCProject_jEhBHrS2-Tumor-SM-CGKTZ        1       1               1   
MBC-MBCProject_kAFQF3t6-Tumor-SM-DL36W       -2      -2              -2   
MBC-MBCProject_kRC3tlcA-Tumor-SM-DL3LY       -1      -1              -1   
MBC-MBCProject_kduys9h5-Tumor-SM-DL46G       -1      -1              -1   
MBC-MBCProject_kduys9h5-Tumor-SM-DL47P        0       0               0   
MBC-MBCProject_kwS1CXSR-Tumor-SM-DL4SG        0       0               0   
MBC-MBCProject_lXCmTEuv-Tumor-SM-DL4WU        0       0               0   
MBC-MBCProject_mrhKt1Ue-Tumor-SM-DL4UY        0       0               0   
MBC-MBCProject_nZHYc4Ie-Tumor-SM-DL39E        0       0               0   
MBC-MBCProject_p1CQTdIg-Tumor-SM-CGL36        0       0               0   
MBC-MBCProject_pMcWcrtZ-Tumor-SM-AZ5KE        0       0               0   
MBC-MBCProject_rJHBiKTl-Tumor-SM-DL3K3        0       0               0   
MBC-MBCProject_rmSBIguN-Tumor-SM-DL385        0       0          

In [143]:
labels

MBC-MBCProject_1ps2hZH8-Tumor-SM-DL4OO    1
MBC-MBCProject_1qhlIasw-Tumor-SM-AXGNH    1
MBC-MBCProject_27uAugT4-Tumor-SM-DL45T    1
MBC-MBCProject_3LI1TNs3-Tumor-SM-DL43B    1
MBC-MBCProject_3MUnT7Ty-Tumor-SM-CGLLE    3
MBC-MBCProject_3jhES9fq-Tumor-SM-AXGIU    2
MBC-MBCProject_43UpSwhz-Tumor-SM-DL4W8    1
MBC-MBCProject_4DIpSBFV-Tumor-SM-CGM2Q    1
MBC-MBCProject_4MF1FlFQ-Tumor-SM-AZ5CU    1
MBC-MBCProject_4MF1FlFQ-Tumor-SM-CGM4M    1
MBC-MBCProject_4OIOfAt9-Tumor-SM-CGLYL    1
MBC-MBCProject_4vC6Fgio-Tumor-SM-CGLZ8    1
MBC-MBCProject_57iLiJIl-Tumor-SM-CGLIV    1
MBC-MBCProject_5jSPs9fl-Tumor-SM-CGL1A    0
MBC-MBCProject_70CxiQFk-Tumor-SM-DL3TI    1
MBC-MBCProject_74CYIyHw-Tumor-SM-DL3P4    1
MBC-MBCProject_7JtRIPI2-Tumor-SM-CGLXC    3
MBC-MBCProject_7JtRIPI2-Tumor-SM-CGMAW    3
MBC-MBCProject_7OcOivcV-Tumor-SM-DL44K    3
MBC-MBCProject_7VFnIqfw-Tumor-SM-CGL6X    1
MBC-MBCProject_7XFmtytw-Tumor-SM-DL457    1
MBC-MBCProject_7of5i3hp-Tumor-SM-CGMAA    1
MBC-MBCProject_99CdCOHm-Tumor-SM

In [145]:
result.shape

(103, 23109)

In [152]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import time

    
randomize = True
if randomize:
    random_indices = np.random.permutation(len(X))
    # Randomized data
    X_r = X[random_indices]
    Y_r = Y[random_indices]


# Remove the excess of example 1 points
reduce_1 = False
if reduce_1:
    drop = np.where(Y_r==1)[0]
    Y_keep = np.random.choice(drop, size=40)
    Y_keep = np.array(list(Y_keep)+list(np.where(Y_r==0)[0]) + list(np.where(Y_r==2)[0]) + list(np.where(Y_r==3)[0]))
    X_r = X_r[Y_keep]
    Y_r = Y_r[Y_keep]
    
    print(X_r.shape)
    
def run_regression(X_r, Y_r, penalty = 'l2', per_train=0.4, per_val=0.15):
    
    # Select a training, test and validation set

    n_train = int(per_train*X_r.shape[0])
    n_val = int(per_val*X_r.shape[0])


    X_test, y_test = X_r[:n_train], Y_r[:n_train]
    X_val, y_val = X_r[n_train:n_train+n_val], Y_r[n_train:n_train+n_val]
    X_train, y_train = X_r[n_train+n_val:], Y_r[n_train+n_val:]

    # How many of each cancer type are in the train, test and validations set?
    tr_count = y_train.value_counts()/np.sum( y_train.value_counts())
    val_count = y_val.value_counts()/np.sum(y_val.value_counts())
    te_count = y_test.value_counts()/np.sum(y_test.value_counts())


    # Plot the distribution of test, train and val points. Will throw a KeyError if any
    try:
        trace1 = go.Bar(
            x=['BREAST','IDC', 'MDLC', 'ILC'],
            y=[tr_count[i] for i in range(4)],
            name='Training Set'
        )
        trace2 = go.Bar(
            x=['BREAST','IDC', 'MDLC', 'ILC'],
            y=[val_count[i] for i in range(4)],
            name='Validation Set'
        )

        trace3 = go.Bar(
            x=['BREAST','IDC', 'MDLC', 'ILC'],
            y=[te_count[i] for i in range(4)],
            name='Test Set'
        )

        data = [trace1, trace2, trace3]
        layout = go.Layout(
            barmode='group',
            title = 'Distribution of Categories over Data Sets',
            xaxis = dict(title = 'Categories'),
            yaxis = dict(title = 'Percentage of Data Set'),
        )

        fig = go.Figure(data=data, layout=layout)
        iplot(fig, filename='grouped-bar')

    except:
        print(tr_count)
        print(val_count)
        print(te_count)
        print('One of the data sets does not contain all the categories!')
        assert False

    # plot the training data in two dimensions
    performPCA(X_train, y_train)
    
    t0 = time.clock()

    train_samples, n_features = X_train.shape
    n_classes = np.unique(Y).shape[0]

    print('Dataset 2CN, train_samples=%i, n_features=%i, n_classes=%i'
          % (train_samples, n_features, n_classes))

    models = {'ovr': {'name': 'One versus Rest', 'iters': [1, 3, 7, 11, 13, 15, 17, 21]},
              'multinomial': {'name': 'Multinomial', 'iters': [1, 3, 7, 11, 13, 15, 17, 21]}}

    # Solver which handles multiclass and l1 penalty
    solver = 'newton-cg'

    if penalty == 'l1':
        print('Using l1 regression')
        models = {'ovr': {'name': 'One versus Rest', 'iters': [1, 3, 7, 11, 13, 15, 17, 21]}}
        solver = 'liblinear'

    best_val_accuracy = 0
    best_model = None 
    
    for model in models:
        # Add initial chance-level values for plotting purpose
        test_accuracies = [1 / n_classes]
        tr_accuracies = [1/n_classes]
        val_accuracies = [1/n_classes]
        times = [0]
        densities = [1]

        model_params = models[model]

        # Small number of epochs for fast runtime
        for this_max_iter in model_params['iters']:
            print('[model=%s, solver=%s] Number of epochs: %s' %
                  (model_params['name'], solver, this_max_iter))
            lr = LogisticRegression(solver=solver,
                                    multi_class=model,
                                    C=1,
                                    penalty=penalty,
                                    fit_intercept=True,
                                    max_iter=this_max_iter,
                                    random_state=42,
                                    )
            
            lr.fit(X_train, y_train)
            
            accuracy = np.sum(y_test == lr.predict(X_test)) / y_test.shape[0]
            density = np.mean(lr.coef_ != 0, axis=1) * 100
            tr_accuracy = np.sum(y_train == lr.predict(X_train)) / y_train.shape[0]
            val_accuracy = np.sum(y_val == lr.predict(X_val)) / y_val.shape[0]

            test_accuracies.append(accuracy)
            densities.append(density)
            tr_accuracies.append(tr_accuracy)
            val_accuracies.append(val_accuracy)
            times.append(this_max_iter)
            
            if accuracy>best_val_accuracy:
                best_model = lr
                
        models[model]['times'] = times
        models[model]['densities'] = densities
        models[model]['test_accuracies'] = test_accuracies
        models[model]['tr_accuracies'] = tr_accuracies
        models[model]['val_accuracies'] = val_accuracies

        print('Test accuracy for model %s: %.4f' % (model, test_accuracies[-1]))
        print('Train accuracy for model %s: %.4f' % (model, tr_accuracies[-1]))
        print('Validation accuracy for model %s: %.4f' % (model, val_accuracies[-1]))
        print('%% non-zero coefficients for model %s, '
              'per class:\n %s' % (model, densities[-1]))
        print('Run time (%i epochs) for model %s:'
              '%.2f' % (model_params['iters'][-1], model, times[-1]))

    fig = plt.figure()
    ax = fig.add_subplot(111)

    for model in models:
        data = []
        for accuracy in ['tr_accuracies', 'val_accuracies','test_accuracies']:
            trace = go.Scatter(
                                x = models[model]['times'],
                                y = models[model][accuracy],
                                name = accuracy
                            )

            data.append(trace)
        layout = go.Layout(
            title = 'Accuracy for {0} model'.format(model),
            xaxis = dict(title = 'Iterations'),
            yaxis = dict(title = 'Accuracy'),
        )

        fig = go.Figure(data=data, layout=layout)
        iplot(fig)

    run_time = time.clock() - t0
    print('Example run in %.3f s' % run_time)

    from sklearn.metrics import confusion_matrix
    c = confusion_matrix(y_test, best_model.predict(X_test))

    trace = go.Heatmap(z=(c.T/np.sum(c,axis=1)).T,                   
                       x=['BREAST','IDC', 'MDLC', 'ILC'],
                       y=['BREAST','IDC', 'MDLC', 'ILC'])
    data=[trace]

    layout = go.Layout(
        title = 'Confusion Matrix for Test Predictions',
        xaxis = dict(title = 'Predicted'),
        yaxis = dict(title = 'Truth'),
    )

    fig = go.Figure(data=data, layout=layout)
    iplot(fig)
    
    c = confusion_matrix(y_train, best_model.predict(X_train))
    trace = go.Heatmap(z=(c.T/np.sum(c,axis=1)).T,                   
                       x=['BREAST','IDC', 'MDLC', 'ILC'],
                       y=['BREAST','IDC', 'MDLC', 'ILC'])
    data=[trace]

    layout = go.Layout(
        title = 'Confusion Matrix for Training Predictions',
        xaxis = dict(title = 'Predicted'),
        yaxis = dict(title = 'Truth'),
    )

    fig = go.Figure(data=data, layout=layout)
    iplot(fig)


    return best_model, lr

In [153]:
lr, last = run_regression(X_r, Y_r, penalty = 'l2')

Defined model
Performing PCA on data with shape (47, 23109)
Variance explained by selected components
[ 0.11933724  0.07462547  0.06911844]


Plotted data
Dataset 2CN, train_samples=47, n_features=23109, n_classes=4
[model=One versus Rest, solver=newton-cg] Number of epochs: 1
[model=One versus Rest, solver=newton-cg] Number of epochs: 3


C:\Users\Sitara\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:203: ConvergenceWarning:

newton-cg failed to converge. Increase the number of iterations.



[model=One versus Rest, solver=newton-cg] Number of epochs: 7
[model=One versus Rest, solver=newton-cg] Number of epochs: 11
[model=One versus Rest, solver=newton-cg] Number of epochs: 13
[model=One versus Rest, solver=newton-cg] Number of epochs: 15
[model=One versus Rest, solver=newton-cg] Number of epochs: 17
[model=One versus Rest, solver=newton-cg] Number of epochs: 21
Test accuracy for model ovr: 0.5250
Train accuracy for model ovr: 1.0000
Validation accuracy for model ovr: 0.6000
% non-zero coefficients for model ovr, per class:
 [ 99.99567268  99.99567268  99.99567268  99.99567268]
Run time (21 epochs) for model ovr:21.00
[model=Multinomial, solver=newton-cg] Number of epochs: 1
[model=Multinomial, solver=newton-cg] Number of epochs: 3
[model=Multinomial, solver=newton-cg] Number of epochs: 7
[model=Multinomial, solver=newton-cg] Number of epochs: 11
[model=Multinomial, solver=newton-cg] Number of epochs: 13
[model=Multinomial, solver=newton-cg] Number of epochs: 15
[model=Mult

C:\Users\Sitara\Anaconda3\lib\site-packages\matplotlib\pyplot.py:524: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).



Example run in 13.253 s


In [78]:
lr_sparse = run_regression(X_r, Y_r, penalty = 'l1')

Defined model
Performing PCA on data with shape (47, 23109)
Variance explained by selected components
[ 0.11233168  0.07415286  0.05941048]


Plotted data
Dataset 2CN, train_samples=47, n_features=23109, n_classes=4
Using l1 regression
[model=One versus Rest, solver=liblinear] Number of epochs: 1
[model=One versus Rest, solver=liblinear] Number of epochs: 3
[model=One versus Rest, solver=liblinear] Number of epochs: 7
[model=One versus Rest, solver=liblinear] Number of epochs: 11
[model=One versus Rest, solver=liblinear] Number of epochs: 13
[model=One versus Rest, solver=liblinear] Number of epochs: 15
Test accuracy for model ovr: 0.5122
Train accuracy for model ovr: 1.0000
Validation accuracy for model ovr: 0.7333
% non-zero coefficients for model ovr, per class:
 [ 0.19472933  0.31156692  0.3072396   0.09952832]
Run time (15 epochs) for model ovr:15.00


C:\Users\Sitara\Anaconda3\lib\site-packages\matplotlib\pyplot.py:524: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).



Example run in 1.449 s


In [137]:
def analyse_LASSO_weights(weights, genes):
    f=open('Useful_Genes.csv','w+')
    useful_genes = {}
    for i,category in enumerate(['BREAST','IDC','MDLC','ILC']):
        f.write('Category, {0} \n'.format(category))
        wt = weights.coef_[i]
        idx = np.where(wt!=0)[0]
        useful_genes[category] = genes[idx]
        for (gene, weight) in list(zip(genes[idx], wt[idx])):
            f.write('{0},{1}\n'.format(gene, weight))
    f.close()
    
    return useful_genes

useful_genes = analyse_LASSO_weights(lr_sparse[0], genes)

In [88]:
imputed = 'PATIENT_DATA_ALL_2.csv'
non_imputed = 'filename_2.txt'

merged = pd.read_csv(imputed, sep='\t', )
labels = pd.read_csv('OLD_DATA/data_clinical_sample_clean.tsv', sep='\t')

labels.set_index('SAMPLE_ID', inplace=True)
labels.drop(['Unnamed: 0'], axis=1, inplace=True)

merged.drop('PATIENT_ID', axis=1,inplace=True)
merged.drop('SAMPLE_ID', axis=1,inplace=True)
merged.drop(['Unnamed: 0'], axis=1,inplace=True)

labels = labels['ONCOTREE_CODE']
result = pd.concat([merged, labels], axis=1)


C:\Users\Sitara\Anaconda3\lib\site-packages\pandas\indexes\range.py:432: RuntimeWarning:

unorderable types: int() < str(), sort order is undefined for incomparable objects



In [92]:

# random_indices = np.random.permutation(len(merged))

# X_randomized = merged.iloc[random_indices]
# Y_randomized = labels[:-1].iloc[random_indices]


sample_lr_l1 = run_regression(X_randomized, Y_randomized, penalty = 'l2')

Defined model
Performing PCA on data with shape (47, 106)
Variance explained by selected components
[  7.58219364e-01   2.41765183e-01   3.78410090e-06]


Plotted data
Dataset 2CN, train_samples=47, n_features=106, n_classes=4
[model=One versus Rest, solver=newton-cg] Number of epochs: 1
[model=One versus Rest, solver=newton-cg] Number of epochs: 3
[model=One versus Rest, solver=newton-cg] Number of epochs: 7
[model=One versus Rest, solver=newton-cg] Number of epochs: 11
[model=One versus Rest, solver=newton-cg] Number of epochs: 13
[model=One versus Rest, solver=newton-cg] Number of epochs: 15


C:\Users\Sitara\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:203: ConvergenceWarning:

newton-cg failed to converge. Increase the number of iterations.



[model=One versus Rest, solver=newton-cg] Number of epochs: 17
[model=One versus Rest, solver=newton-cg] Number of epochs: 21
Test accuracy for model ovr: 0.6750
Train accuracy for model ovr: 0.9149
Validation accuracy for model ovr: 0.5333
% non-zero coefficients for model ovr, per class:
 [ 80.18867925  80.18867925  80.18867925  80.18867925]
Run time (21 epochs) for model ovr:21.00
[model=Multinomial, solver=newton-cg] Number of epochs: 1
[model=Multinomial, solver=newton-cg] Number of epochs: 3
[model=Multinomial, solver=newton-cg] Number of epochs: 7
[model=Multinomial, solver=newton-cg] Number of epochs: 11
[model=Multinomial, solver=newton-cg] Number of epochs: 13
[model=Multinomial, solver=newton-cg] Number of epochs: 15
[model=Multinomial, solver=newton-cg] Number of epochs: 17
[model=Multinomial, solver=newton-cg] Number of epochs: 21
Test accuracy for model multinomial: 0.6500
Train accuracy for model multinomial: 0.9362
Validation accuracy for model multinomial: 0.5333
% non

C:\Users\Sitara\Anaconda3\lib\site-packages\matplotlib\pyplot.py:524: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).



Example run in 1.604 s


In [142]:
import seaborn as sns

for category in useful_genes:
    g = useful_genes[category]
    useful_data = data[g]
    display(useful_data.head())
    sns.clustermap(useful_data, metric="correlation")
    sns.plt.show()


Hugo_Symbol                             HNRNPH1  IKBKB  MIR3610  MAF1  SHB  \
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5H9        0      0        1     0    0   
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5HV        0      0        0     0    0   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGLTK        0      0        0     0    0   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGMGK        2      0        1     1    0   
MBC-MBCProject_4MF1FlFQ-Tumor-SM-AZ5CU        0      0        2     2    0   

Hugo_Symbol                             ALDH1B1  CDH23  CCND1  DYNC2H1  MYH6  \
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5H9        0     -1      0        0     0   
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5HV        0     -1      0        0     0   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGLTK        0      0      0        0     0   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGMGK        0     -1      0        0    -1   
MBC-MBCProject_4MF1FlFQ-Tumor-SM-AZ5CU        0     -1      0        0     0   

Hugo_Symbol                             ...    SNORD115-40  SNORD115-41  \
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5H9  ...             -1           -1   
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5HV  ...              0            0   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGLTK  ...             -2           -2   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGMGK  ...             -2           -2   
MBC-MBCProject_4MF1FlFQ-Tumor-SM-AZ5CU  ...             -1           -1   

Hugo_Symbol                             SNORD115-42  IRX3  CRNDE  IRX5  MT3  \
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5H9           -1     0      0     0   -1   
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5HV            0     0      0     0   -1   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGLTK           -2     0      0     0    0   
MBC-MBCProject_N4srsKsr-Tumor-SM-CGMGK           -2     1      1     1   -1   
MBC-MBCProject_4MF1FlFQ-Tumor-SM-AZ5CU           -1     2      0    -1   -1   

Hugo_Symbol                             C16orf48  CCDC56  MIER2  
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5H9        -1       0      0  
MBC-MBCProject_GvHkH2Hk-Tumor-SM-AZ5HV         1       0      0  
MBC-MBCProject_N4srsKsr-Tumor-SM-CGLTK         2       0      0  
MBC-MBCProject_N4srsKsr-Tumor-SM-CGMGK        -1       0      0  
MBC-MBCProject_4MF1FlFQ-Tumor-SM-AZ5CU         2       0     -1  

[5 rows x 23 columns]

C:\Users\Sitara\Anaconda3\lib\site-packages\matplotlib\pyplot.py:524: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

C:\Users\Sitara\Anaconda3\lib\site-packages\matplotlib\cbook.py:136: MatplotlibDeprecationWarning:

The axisbg attribute was deprecated in version 2.0. Use facecolor instead.



ValueError: The condensed distance matrix must contain only finite values.